name:                haskdice
version:             1.0.2.0
github:              "github.com/ZimmSebas/HasKDice"
license:             GNU3
author:              "Zimmermann Sebastian"
maintainer:          "example@example.com"
copyright:           "2020 ZimmSebas"

extra-source-files:
- README.md
- ToDo.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/ZimmSebas/HaskDice#readme>

dependencies:
- base >= 4.7 && < 5
- readline >= 1.0.2
- random
- parsec

library:
  source-dirs: src

executables:
  haskdice:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskdice

tests:
  haskdice-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskdice
